project:
  type: website

website:
  page-navigation: true
  title: "Jinwoo"
  page-footer:
    left: "&copy; Copyright 2025, Jinwoo Go"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
  sidebar:
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    search: true
    back-to-top-navigation: true
    contents:
      - text: "About me"
        href: index.qmd
      - text: "Research"
        href: research/index.qmd
    tools:
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/jinwoo-go-6b1485199/
      - icon: github
        text: Github
        href: https://github.com/JinuG6328

reader-mode: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true